runtime: python27
api_version: 1
threadsafe: false

handlers:
  - url: /robots\.txt
    static_files: static/robots.txt
    upload: static/robots\.txt
    secure: always
    redirect_http_response_code: 301

  - url: /static
    static_dir: static
    secure: always
    redirect_http_response_code: 301

  - url: /.*
    script: redirect.py
    secure: always
    redirect_http_response_code: 301
